export enum UserStatus {
	AVAILABLE = "AVAILABLE",
	PRIORITY_TASK_IN_PROGRESS = "PRIORITY TASK IN PROGRESS" ,
	ON_LEAVE = "ON LEAVE",
	POC_IN_PROGRESS = "POC IN PROGRESS",
	TASK_IN_PROGRESS = "TASK IN PROGRESS",
}